/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as RefundCancellationPolicyRouteImport } from './routes/refund-cancellation-policy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ApiScanBillRouteImport } from './routes/api/scan-bill'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiPublicAiAdviceRouteImport } from './routes/api/public/ai-advice'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'
import { Route as ApiPublicPayuReturnRouteImport } from './routes/api/public/payu-return'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundCancellationPolicyRoute =
  RefundCancellationPolicyRouteImport.update({
    id: '/refund-cancellation-policy',
    path: '/refund-cancellation-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanBillRoute = ApiScanBillRouteImport.update({
  id: '/api/scan-bill',
  path: '/api/scan-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiAdviceRoute = ApiPublicAiAdviceRouteImport.update({
  id: '/api/public/ai-advice',
  path: '/api/public/ai-advice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPayuReturnRoute = ApiPublicPayuReturnRouteImport.update({
  id: '/api/public/payu-return',
  path: '/api/public/payu-return',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/contact-us': typeof ContactUsRoute
  '/debts': typeof DebtsRoute
  '/ledger': typeof LedgerRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/settings': typeof SettingsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/transactions': typeof TransactionsRoute
  '/api/scan-bill': typeof ApiScanBillRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/ai-advice': typeof ApiPublicAiAdviceRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/public/payu-return': typeof ApiPublicPayuReturnRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/contact-us': typeof ContactUsRoute
  '/debts': typeof DebtsRoute
  '/ledger': typeof LedgerRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/settings': typeof SettingsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/transactions': typeof TransactionsRoute
  '/api/scan-bill': typeof ApiScanBillRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/ai-advice': typeof ApiPublicAiAdviceRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/public/payu-return': typeof ApiPublicPayuReturnRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/contact-us': typeof ContactUsRoute
  '/debts': typeof DebtsRoute
  '/ledger': typeof LedgerRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/refund-cancellation-policy': typeof RefundCancellationPolicyRoute
  '/settings': typeof SettingsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/transactions': typeof TransactionsRoute
  '/api/scan-bill': typeof ApiScanBillRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/ai-advice': typeof ApiPublicAiAdviceRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
  '/api/public/payu-return': typeof ApiPublicPayuReturnRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/contact-us'
    | '/debts'
    | '/ledger'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/receipts'
    | '/refund-cancellation-policy'
    | '/settings'
    | '/shipping-policy'
    | '/terms-and-conditions'
    | '/transactions'
    | '/api/scan-bill'
    | '/api/tts'
    | '/api/public/ai-advice'
    | '/api/public/cashfree-webhook'
    | '/api/public/payu-return'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/contact-us'
    | '/debts'
    | '/ledger'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/receipts'
    | '/refund-cancellation-policy'
    | '/settings'
    | '/shipping-policy'
    | '/terms-and-conditions'
    | '/transactions'
    | '/api/scan-bill'
    | '/api/tts'
    | '/api/public/ai-advice'
    | '/api/public/cashfree-webhook'
    | '/api/public/payu-return'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/contact-us'
    | '/debts'
    | '/ledger'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/receipts'
    | '/refund-cancellation-policy'
    | '/settings'
    | '/shipping-policy'
    | '/terms-and-conditions'
    | '/transactions'
    | '/api/scan-bill'
    | '/api/tts'
    | '/api/public/ai-advice'
    | '/api/public/cashfree-webhook'
    | '/api/public/payu-return'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContactUsRoute: typeof ContactUsRoute
  DebtsRoute: typeof DebtsRoute
  LedgerRoute: typeof LedgerRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RefundCancellationPolicyRoute: typeof RefundCancellationPolicyRoute
  SettingsRoute: typeof SettingsRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiScanBillRoute: typeof ApiScanBillRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicAiAdviceRoute: typeof ApiPublicAiAdviceRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
  ApiPublicPayuReturnRoute: typeof ApiPublicPayuReturnRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-cancellation-policy': {
      id: '/refund-cancellation-policy'
      path: '/refund-cancellation-policy'
      fullPath: '/refund-cancellation-policy'
      preLoaderRoute: typeof RefundCancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan-bill': {
      id: '/api/scan-bill'
      path: '/api/scan-bill'
      fullPath: '/api/scan-bill'
      preLoaderRoute: typeof ApiScanBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-advice': {
      id: '/api/public/ai-advice'
      path: '/api/public/ai-advice'
      fullPath: '/api/public/ai-advice'
      preLoaderRoute: typeof ApiPublicAiAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payu-return': {
      id: '/api/public/payu-return'
      path: '/api/public/payu-return'
      fullPath: '/api/public/payu-return'
      preLoaderRoute: typeof ApiPublicPayuReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContactUsRoute: ContactUsRoute,
  DebtsRoute: DebtsRoute,
  LedgerRoute: LedgerRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ReceiptsRoute: ReceiptsRoute,
  RefundCancellationPolicyRoute: RefundCancellationPolicyRoute,
  SettingsRoute: SettingsRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TransactionsRoute: TransactionsRoute,
  ApiScanBillRoute: ApiScanBillRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicAiAdviceRoute: ApiPublicAiAdviceRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
  ApiPublicPayuReturnRoute: ApiPublicPayuReturnRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
