/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiScanBillRouteImport } from './routes/api/scan-bill'
import { Route as ApiPublicAiAdviceRouteImport } from './routes/api/public/ai-advice'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanBillRoute = ApiScanBillRouteImport.update({
  id: '/api/scan-bill',
  path: '/api/scan-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiAdviceRoute = ApiPublicAiAdviceRouteImport.update({
  id: '/api/public/ai-advice',
  path: '/api/public/ai-advice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/debts': typeof DebtsRoute
  '/settings': typeof SettingsRoute
  '/api/scan-bill': typeof ApiScanBillRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/ai-advice': typeof ApiPublicAiAdviceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/debts': typeof DebtsRoute
  '/settings': typeof SettingsRoute
  '/api/scan-bill': typeof ApiScanBillRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/ai-advice': typeof ApiPublicAiAdviceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/debts': typeof DebtsRoute
  '/settings': typeof SettingsRoute
  '/api/scan-bill': typeof ApiScanBillRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/ai-advice': typeof ApiPublicAiAdviceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/analytics'
    | '/debts'
    | '/settings'
    | '/api/scan-bill'
    | '/api/tts'
    | '/api/public/ai-advice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/analytics'
    | '/debts'
    | '/settings'
    | '/api/scan-bill'
    | '/api/tts'
    | '/api/public/ai-advice'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/analytics'
    | '/debts'
    | '/settings'
    | '/api/scan-bill'
    | '/api/tts'
    | '/api/public/ai-advice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DebtsRoute: typeof DebtsRoute
  SettingsRoute: typeof SettingsRoute
  ApiScanBillRoute: typeof ApiScanBillRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicAiAdviceRoute: typeof ApiPublicAiAdviceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan-bill': {
      id: '/api/scan-bill'
      path: '/api/scan-bill'
      fullPath: '/api/scan-bill'
      preLoaderRoute: typeof ApiScanBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-advice': {
      id: '/api/public/ai-advice'
      path: '/api/public/ai-advice'
      fullPath: '/api/public/ai-advice'
      preLoaderRoute: typeof ApiPublicAiAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  DebtsRoute: DebtsRoute,
  SettingsRoute: SettingsRoute,
  ApiScanBillRoute: ApiScanBillRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicAiAdviceRoute: ApiPublicAiAdviceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
